# ----------------------------
# Makefile Options
# ----------------------------

NAME = QUAD
ICON = icon.png
DESCRIPTION = "Program to Solve Quadratic Equations"
COMPRESSED = YES

CFLAGS = -Wall -Wextra -Oz -Os
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
